[project]
name = "digit-recognition"
version = "0.1.0"
requires-python = "==3.11.*"
dependencies = [
    "tflite-runtime",
    "Flask",
    "numpy",
    "pillow",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
